In [1]:
import numpy as np
np.ones(shape=3)


array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
np.ones(shape=(2, 3)) # dimension 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones(shape=(2, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [6]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [7]:
a[1, 1] = 18
a

array([[ 1.,  1.],
       [ 1., 18.]])

In [8]:
np.sctypes

{'complex': [numpy.complex64, numpy.complex128, numpy.complex256],
 'float': [numpy.float16, numpy.float32, numpy.float64, numpy.float128],
 'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'others': [bool, object, bytes, str, numpy.void],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]}

In [9]:
a = np.array([1, 100, 110], dtype=np.int8)
a

array([  1, 100, 110], dtype=int8)

In [10]:
a.dtype

dtype('int8')

In [11]:
a.itemsize

1

In [12]:
a.nbytes

3

In [19]:
np.array([1, 4.5, 128], dtype=np.int8)    #int8 = -128 to 127


array([   1,    4, -128], dtype=int8)

In [20]:
a = np.array([1, 2, np.nan])
a.dtype

dtype('float64')

In [21]:
np.sctypes['others']

[bool, object, bytes, str, numpy.void]

In [22]:
a = np.array(['spam', 'beans'], dtype=np.str)
a

array(['spam', 'beans'], dtype='<U5')

In [24]:
a = np.array(['spam', 'beans'], dtype=(np.str,2))
a

array(['sp', 'be'], dtype='<U2')

In [25]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[3, 3, 9],
       [6, 4, 5],
       [6, 7, 1]])

In [26]:
a[1:, 2:]     # Slicing

array([[5],
       [1]])

In [27]:
b = a[1:, :2]
b

array([[6, 4],
       [6, 7]])

In [29]:
a = np.random.randint(1, 10, size=(4, 4))
a

array([[6, 3, 7, 7],
       [4, 1, 2, 9],
       [7, 2, 9, 6],
       [4, 3, 5, 8]])

In [30]:
b = a.reshape(8, 2)    # Reshaping
b

array([[6, 3],
       [7, 7],
       [4, 1],
       [2, 9],
       [7, 2],
       [9, 6],
       [4, 3],
       [5, 8]])

In [31]:
mars = np.random.randint(-5, 20, size=31)
mars

array([-2, 16,  4, 16, -4, 12,  9, 16,  5, 13,  0,  3, 11, 17,  7, 14,  6,
        4,  3, 16,  5,  3, -2, 13,  5, 10,  7,  4, -4,  1,  7])

In [32]:
mars > 0

array([False,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True])

In [33]:
mars == 0

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False])

In [34]:
np.sum(mars > 0)

26

In [35]:
np.any(mars == 20)

False

In [36]:
np.all(mars > 0)

False

In [37]:
jours_mars = np.arange(1, mars.size + 1, dtype=np.int8)
jours_mars

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31], dtype=int8)

In [39]:
np.sum((mars > 10) & (jours_mars >= 15))

4

In [40]:
mars[mars > 10]    # indexation

array([16, 16, 12, 16, 13, 11, 17, 14, 16, 13])

In [41]:
mars[(mars > 10) & (jours_mars >= 15)]

array([14, 16, 13])

In [43]:
moy = np.mean(mars[mars > 0])
mars[mars < 0] = moy
mars

array([ 8, 16,  4, 16,  8, 12,  9, 16,  5, 13,  0,  3, 11, 17,  7, 14,  6,
        4,  3, 16,  5,  3,  8, 13,  5, 10,  7,  4,  8,  1,  7])

In [44]:
pays = np.array(['fr', 'uk', 'cn'])
pays[[0, 0, 1, 2, 0]]

array(['fr', 'fr', 'uk', 'cn', 'fr'], dtype='<U2')

In [2]:
import numpy as np
a = np.arange(1, 10).reshape(3, 3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(a)

45

In [4]:
np.sum(a, axis=0)    # somme de la colonne 

array([12, 15, 18])

In [5]:
np.sum(a, axis=1)    # somme de la ligne

array([ 6, 15, 24])

In [6]:
a = np.arange(1, 10, dtype = np.float64).reshape(3, 3)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [7]:
a[1, 1] = np.nan
a

array([[ 1.,  2.,  3.],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [8]:
np.mean(a)

nan

In [9]:
np.nanmean(a)    # ignore nan

5.0